id: P007906
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-17 12:48:28.469440
source_metadata:
  id: bdr:W30172
  title: བཀྲ་ཤིས་ལྷུན་པོ་དཀྱིལ་ཁང་གྲྭ་ཚང་གི་དབུ་མའི་ཡིག་ཆ།
  author: ''
  volumes:
    8dc407b63b3b4d90851573b1630edecd:
      image_group_id: I5956
      title: ''
      volume_number: 1
      total_pages: 473
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
