id: P007906
initial_creation_type: ocr
source_metadata:
  id: bdr:W30172
  title: བཀྲ་ཤིས་ལྷུན་པོ་དཀྱིལ་ཁང་གྲྭ་ཚང་གི་དབུ་མའི་ཡིག་ཆ།
  author: ''
  volumes:
    393499a9acef484b848e53b85ef084f2:
      image_group_id: I5956
      title: ''
      volume_number: 1
      total_pages: 473
ebook_metadata:
  title: བཀྲ་ཤིས་ལྷུན་པོ་དཀྱིལ་ཁང་གྲྭ་ཚང་གི་དབུ་མའི་ཡིག་ཆ།
  author: ''
  sku: P007906
  cover: cover.jpg
  layers:
  - pagination
