id: P007906
initial_creation_type: ocr
source_metadata:
  id: bdr:W30172
  title: བཀྲ་ཤིས་ལྷུན་པོ་དཀྱིལ་ཁང་གྲྭ་ཚང་གི་དབུ་མའི་ཡིག་ཆ།
  author: ''
  volumes:
    8dc407b63b3b4d90851573b1630edecd:
      image_group_id: I5956
      title: ''
      volume_number: 1
      total_pages: 473
      base_file: v001.txt
ebook_metadata:
  title: བཀྲ་ཤིས་ལྷུན་པོ་དཀྱིལ་ཁང་གྲྭ་ཚང་གི་དབུ་མའི་ཡིག་ཆ།
  author: ''
  sku: P007906
  cover: cover.jpg
  layers:
  - pagination
